### ISSUE TITLE
Startup fails

### ISSUE THREAD

**Issue by ina6ra** [camenduru/stable-diffusion-webui-modal#2]
The following error message appears and the startup fails.

```
Launching Web UI with arguments: --xformers --skip-torch-cuda-test --theme dark --gradio-debug --share
Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 304: OS call failed or operation not supported on this OS: str
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/errors.py", line 84, in run
    code()
  File "/content/stable-diffusion-webui/modules/devices.py", line 63, in enable_tf32
    if any(torch.cuda.get_device_capability(devid) == (7, 5) for devid in range(0, torch.cuda.device_count())):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/stable-diffusion-webui/modules/devices.py", line 63, in <genexpr>
    if any(torch.cuda.get_device_capability(devid) == (7, 5) for devid in range(0, torch.cuda.device_count())):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 304: OS call failed or operation not supported on this OS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 352, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 510, in run_input
    value = await res
            ^^^^^^^^^
  File "/root/run0.py", line 48, in run
    launch_utils.start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/stable-diffusion-webui/modules/initialize.py", line 34, in imports
    shared_init.initialize()
  File "/content/stable-diffusion-webui/modules/shared_init.py", line 17, in initialize
    from modules import options, shared_options
  File "/content/stable-diffusion-webui/modules/shared_options.py", line 3, in <module>
    from modules import localization, ui_components, shared_items, shared, interrogate, shared_gradio_themes
  File "/content/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "/content/stable-diffusion-webui/modules/devices.py", line 70, in <module>
    errors.run(enable_tf32, "Enabling TF32")
  File "/content/stable-diffusion-webui/modules/errors.py", line 86, in run
    display(task, e)
  File "/content/stable-diffusion-webui/modules/errors.py", line 54, in display
    te = traceback.TracebackException.from_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/traceback.py", line 790, in from_exception
    return cls(type(exc), exc, exc.__traceback__, *args, **kwargs)
                               ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '__traceback__'
```

**Comment by ina6ra** [comment]
I have posted the same information to the repository where the file in question is located.
I was able to partially solve the problem and will post the rest there.

https://github.com/camenduru/webui-modal/issues/1
